### PR TITLE
Migrate code to Swift4

### PR DESCRIPTION
**Pull request by bejo**
* Migrated code to Swift 4.

### CODE REVIEW

**Review by paweldudek — APPROVED** [review]
👍

**Comment by paweldudek** [comment]
@bejo can we also send this upstream?

**Comment by bejo** [comment]
I'm afraid that would be pointless. Looks like the autor of this pod stopped updating it recently :( Just have a look at the upstream:
screen shot 2017-11-21 at 15 40 27

**Comment by paweldudek** [comment]
Yeah, I checked that after I wrote that message. Let's leave it as is then.

**Pull request merged**
